### ISSUE TITLE
Excluding domains

### ISSUE THREAD

**Issue by fortin** [username0x0a/Tamperish#9]
Is it possible to exclude a domain, so that Tamperish doesn't apply global scripts to it? I have in mind something like Tampermonkey's `@exclude` parameter.  Thanks.

**Comment by username0x0a** [comment]
Not at this moment, unfortunately. 🤔 But I have this listed somewhere as one of the features to cover with priority, to have some matching with classic Tampermonkey scripts. 💡

In the meantime, I guess you could wrap the code and opt out programatically by evaluating some condition on top of `window.location`.

**Comment by fortin** [comment]
> In the meantime, I guess you could wrap the code and opt out programatically by evaluating some condition on top of `window.location`.

Obvious workaround really, I should've thought of that ☺ Thanks.
